"""Add estimated_time, complexity, parent_task_id, and user_id to tasks

Revision ID: a1b2c3d4e5f6
Revises: 911f5c193c80
Create Date: 2026-03-07 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '911f5c193c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_time', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tasks', sa.Column('complexity', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Add foreign key constraint for parent_task_id
    op.create_foreign_key('fk_tasks_parent_task_id', 'tasks', 'tasks', ['parent_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_parent_task_id', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'complexity')
    op.drop_column('tasks', 'estimated_time')
    # ### end Alembic commands ###
